version: '3.4'

networks:
  k6:
  grafana:

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
      - k6
      - grafana
    volumes:
      - ./prometheus:/etc/prometheus
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:9.3.8
    container_name: grafana
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/etc/grafana/provisioning/

  image_generator:
    image: node:20
    container_name: image_generator
    depends_on:
      - imgproxy_1
    networks:
      - k6
    volumes:
      - ./img:/imgs:rw
      - ./scripts:/scripts
    entrypoint:
      - node
      - /scripts/CompressedImages.js

  k6:
    image: grafana/k6:master-with-browser
    container_name: k6
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./examples:/scripts
    depends_on:
      - image_generator
      - imgproxy_1
    entrypoint: 
     - k6 
     - run 
     - /scripts/script.js

  imgproxy_1:
    image: darthsim/imgproxy:latest
    container_name: imgproxy_1
    networks:
      - k6
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - IMGPROXY_LOCAL_FILESYSTEM_ROOT=/imgs/
      - IMGPROXY_PROMETHEUS_BIND=0.0.0.0:8081
      - IMGPROXY_MAX_SRC_RESOLUTION=100
      - IMGPROXY_WRITE_TIMEOUT=40
    volumes:
      - ./img:/imgs
